version: "3.7"

services:

  ionic-dev:
    image: tgmti/portinari-ionic
    ports:
      - 8100:8100
      - 8200:8200
      - 4200:4200
    volumes:
      - .:/app
    entrypoint: bash
    tty: true
    environment:
      - INIT_IONIC_SERVER=false
      - INIT_IONIC_LAB=false

volumes:
  app: